<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ATMECSINLT-060" failures="1" tests="3" name="com.atmecs.qa.falcondashboard.testscript.TC17_RecentRuns" time="178.184" errors="0" timestamp="16 Mar 2020 14:17:20 GMT" skipped="0">
  <testcase classname="com.atmecs.qa.falcondashboard.testscript.TC17_RecentRuns" name="recentrun" time="49.122"/>
  <testcase classname="com.atmecs.qa.falcondashboard.testscript.TC17_RecentRuns" name="recentrun" time="77.012">
    <failure message="Validating the Dashboard is same as expected or not expected [Recent Runs] but found [Dashboard]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Validating the Dashboard is same as expected or not expected [Recent Runs] but found [Dashboard]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.atmecs.qa.falcondashboard.helper.ValidationHelper.getDataofRow(ValidationHelper.java:28)
at com.atmecs.qa.falcondashboard.validationresults.RecentrunsValidation.validateText(RecentrunsValidation.java:19)
at com.atmecs.qa.falcondashboard.testscript.TC17_RecentRuns.recentrun(TC17_RecentRuns.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
    </failure>
  </testcase> <!-- recentrun -->
  <testcase classname="com.atmecs.qa.falcondashboard.testscript.TC17_RecentRuns" name="recentrun" time="52.050"/>
</testsuite> <!-- com.atmecs.qa.falcondashboard.testscript.TC17_RecentRuns -->
